<?php
/** Create or edit an artist, track, or clip record. */
global $wpdb;
$page = sanitize_key( wp_unslash( $_GET['page'] ?? 'charts-artists' ) );
$type = sanitize_key( wp_unslash( $_GET['type'] ?? ( $page === 'charts-tracks' ? 'track' : ( $page === 'charts-clips' ? 'video' : 'artist' ) ) ) );
$types = array( 'artist' => 'artists', 'track' => 'tracks', 'video' => 'videos' );
if ( ! isset( $types[ $type ] ) ) $type = 'artist';
$page = $type === 'artist' ? 'charts-artists' : ( $type === 'track' ? 'charts-tracks' : 'charts-clips' );
$id = absint( $_GET['id'] ?? 0 );
$table = $wpdb->prefix . 'charts_' . $types[ $type ];
$entity = $id ? $wpdb->get_row( $wpdb->prepare( "SELECT * FROM $table WHERE id = %d", $id ) ) : null;
$artists = $type !== 'artist' ? $wpdb->get_results( "SELECT id, display_name FROM {$wpdb->prefix}charts_artists ORDER BY display_name ASC LIMIT 5000" ) : array();
$tracks = $type === 'video' ? $wpdb->get_results( "SELECT id, title FROM {$wpdb->prefix}charts_tracks ORDER BY title ASC LIMIT 5000" ) : array();
$kind = $type === 'artist' ? __( 'Artist', 'charts' ) : ( $type === 'track' ? __( 'Track', 'charts' ) : __( 'Clip', 'charts' ) );
$name = $entity ? ( $type === 'artist' ? $entity->display_name : $entity->title ) : '';
$image = $entity ? ( $type === 'artist' ? $entity->image : ( $type === 'track' ? $entity->cover_image : $entity->thumbnail ) ) : '';
?>
<div class="wrap charts-admin-wrap premium-light entity-edit-page">
	<header class="charts-admin-header"><div><p class="entity-edit-eyebrow"><?php esc_html_e( 'CANONICAL LIBRARY', 'charts' ); ?></p><h1 class="charts-admin-title"><?php echo esc_html( $id ? sprintf( __( 'Edit %s', 'charts' ), $kind ) : sprintf( __( 'Add %s', 'charts' ), $kind ) ); ?></h1><p class="charts-admin-subtitle"><?php esc_html_e( 'Update this record as it appears in charts and entity matching.', 'charts' ); ?></p></div><a class="charts-btn-back" href="<?php echo esc_url( admin_url( 'admin.php?page=' . $page ) ); ?>">&larr; <?php esc_html_e( 'Back to library', 'charts' ); ?></a></header>
	<?php if ( $id && ! $entity ) : ?><div class="notice notice-error"><p><?php esc_html_e( 'This record could not be found.', 'charts' ); ?></p></div><?php else : ?>
	<form method="post" class="entity-edit-card">
		<?php wp_nonce_field( 'charts_admin_action' ); ?><input type="hidden" name="charts_action" value="save_entity"><input type="hidden" name="entity_type" value="<?php echo esc_attr( $type ); ?>"><input type="hidden" name="entity_id" value="<?php echo (int) $id; ?>">
		<div class="entity-edit-card-head"><span class="dashicons <?php echo esc_attr( $type === 'artist' ? 'dashicons-groups' : ( $type === 'track' ? 'dashicons-playlist-audio' : 'dashicons-video-alt3' ) ); ?>"></span><div><strong><?php echo esc_html( $kind ); ?> <?php esc_html_e( 'details', 'charts' ); ?></strong><small><?php echo $id ? esc_html( sprintf( __( 'Record ID #%d', 'charts' ), $id ) ) : esc_html__( 'New library record', 'charts' ); ?></small></div></div>
		<div class="entity-edit-fields">
			<div class="entity-edit-field wide"><label for="entity-name"><?php echo esc_html( $type === 'artist' ? __( 'Arabic display name', 'charts' ) : __( 'Arabic title', 'charts' ) ); ?></label><input id="entity-name" name="entity_name" type="text" value="<?php echo esc_attr( $name ); ?>" required></div>
			<div class="entity-edit-field"><label for="entity-slug"><?php esc_html_e( 'English slug', 'charts' ); ?></label><input id="entity-slug" name="slug" type="text" value="<?php echo esc_attr( $entity->slug ?? '' ); ?>" placeholder="<?php esc_attr_e( 'Generated from the name if blank', 'charts' ); ?>" dir="ltr"></div>
			<?php if ( $type === 'artist' ) : ?>
				<div class="entity-edit-field"><label for="entity-name-en"><?php esc_html_e( 'English artist name (optional)', 'charts' ); ?></label><input id="entity-name-en" name="name_en" type="text" value="<?php echo esc_attr( $entity->display_name_en ?? '' ); ?>" dir="ltr"></div>
				<div class="entity-edit-field"><label for="entity-spotify"><?php esc_html_e( 'Spotify ID', 'charts' ); ?></label><input id="entity-spotify" name="spotify_id" type="text" value="<?php echo esc_attr( $entity->spotify_id ?? '' ); ?>" dir="ltr"></div>
			<?php else : ?>
				<div class="entity-edit-field"><label for="entity-artist"><?php esc_html_e( 'Primary artist', 'charts' ); ?></label><select id="entity-artist" name="primary_artist_id" required><option value=""><?php esc_html_e( 'Select artist', 'charts' ); ?></option><?php foreach ( $artists as $artist ) : ?><option value="<?php echo (int) $artist->id; ?>" <?php selected( (int) ( $entity->primary_artist_id ?? 0 ), (int) $artist->id ); ?>><?php echo esc_html( $artist->display_name ); ?> (#<?php echo (int) $artist->id; ?>)</option><?php endforeach; ?></select></div>
				<?php if ( $type === 'track' ) : ?><div class="entity-edit-field"><label for="entity-spotify"><?php esc_html_e( 'Spotify ID', 'charts' ); ?></label><input id="entity-spotify" name="spotify_id" type="text" value="<?php echo esc_attr( $entity->spotify_id ?? '' ); ?>" dir="ltr"></div><?php endif; ?>
				<div class="entity-edit-field"><label for="entity-youtube"><?php esc_html_e( 'YouTube ID', 'charts' ); ?></label><input id="entity-youtube" name="youtube_id" type="text" value="<?php echo esc_attr( $entity->youtube_id ?? '' ); ?>" dir="ltr"></div>
				<?php if ( $type === 'video' ) : ?><div class="entity-edit-field"><label for="entity-video-url"><?php esc_html_e( 'Video URL', 'charts' ); ?></label><input id="entity-video-url" name="video_url" type="url" value="<?php echo esc_attr( $entity->video_url ?? '' ); ?>" dir="ltr"></div><div class="entity-edit-field"><label for="entity-related-track"><?php esc_html_e( 'Related track (optional)', 'charts' ); ?></label><select id="entity-related-track" name="related_track_id"><option value="0"><?php esc_html_e( 'No related track', 'charts' ); ?></option><?php foreach ( $tracks as $track ) : ?><option value="<?php echo (int) $track->id; ?>" <?php selected( (int) ( $entity->related_track_id ?? 0 ), (int) $track->id ); ?>><?php echo esc_html( $track->title ); ?> (#<?php echo (int) $track->id; ?>)</option><?php endforeach; ?></select></div><?php endif; ?>
			<?php endif; ?>
			<div class="entity-edit-field wide"><label for="entity-image"><?php echo esc_html( $type === 'artist' ? __( 'Artist image URL', 'charts' ) : ( $type === 'track' ? __( 'Cover image URL', 'charts' ) : __( 'Thumbnail URL', 'charts' ) ) ); ?></label><input id="entity-image" name="image" type="url" value="<?php echo esc_attr( $image ); ?>" dir="ltr"><?php if ( $image ) : ?><img class="entity-edit-preview" src="<?php echo esc_url( $image ); ?>" alt=""><?php endif; ?></div>
		</div>
		<footer class="entity-edit-footer"><a class="button" href="<?php echo esc_url( admin_url( 'admin.php?page=' . $page ) ); ?>"><?php esc_html_e( 'Cancel', 'charts' ); ?></a><button type="submit" class="button button-primary"><span class="dashicons dashicons-saved" aria-hidden="true"></span><?php esc_html_e( 'Save changes', 'charts' ); ?></button></footer>
	</form><?php endif; ?>
</div>
<style>
.entity-edit-page{max-width:1080px}.entity-edit-eyebrow{margin:0 0 5px;color:#5e54b2;font-size:10px;font-weight:800;letter-spacing:.13em}.entity-edit-card{max-width:860px;margin-top:23px;border:1px solid #e4e8f0;border-radius:14px;background:#fff;box-shadow:0 12px 32px rgba(28,39,63,.06)}.entity-edit-card-head{display:flex;align-items:center;gap:12px;padding:20px 24px;border-bottom:1px solid #edf0f5}.entity-edit-card-head>.dashicons{display:grid;place-items:center;width:42px;height:42px;border-radius:11px;background:#f1efff;color:#5c49b6;font-size:21px}.entity-edit-card-head div{display:flex;flex-direction:column;gap:3px;color:#273247}.entity-edit-card-head small{color:#8a94a6;font-size:11px}.entity-edit-fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;padding:24px}.entity-edit-field{display:flex;flex-direction:column;gap:7px;min-width:0}.entity-edit-field.wide{grid-column:1/-1}.entity-edit-field label{color:#3d485c;font-size:12px;font-weight:700}.entity-edit-field input,.entity-edit-field select{width:100%;min-height:42px;border:1px solid #dce1ea;border-radius:7px;padding:8px 11px;color:#1f2937}.entity-edit-field input:focus,.entity-edit-field select:focus{border-color:#6a58c7;box-shadow:0 0 0 3px rgba(106,88,199,.12);outline:0}.entity-edit-preview{width:72px;height:72px;margin-top:3px;border-radius:10px;object-fit:cover}.entity-edit-footer{display:flex;justify-content:flex-end;gap:9px;padding:16px 24px;border-top:1px solid #edf0f5;background:#fafbfc;border-radius:0 0 14px 14px}.entity-edit-footer .button-primary{display:inline-flex;align-items:center;gap:6px;background:#5644b6;border-color:#5644b6}.entity-edit-footer .button-primary .dashicons{font-size:16px;width:16px;height:16px}@media(max-width:600px){.entity-edit-fields{grid-template-columns:1fr;padding:18px}.entity-edit-field.wide{grid-column:auto}.entity-edit-card-head,.entity-edit-footer{padding-left:18px;padding-right:18px}}
</style>
